### ISSUE TITLE
Document "blah" field in package.json

### ISSUE THREAD

**Issue by bfred-it** [IonicaBizau/blah#38]
I can't find the documentation for the the `blah` field, can you add it?

**Comment by IonicaBizau** [comment]
Um, good point! :+1: 

The `blah` field is directly interpreted by the `README.ejs` template. 

For convenience, it's by default an empty object (so additional checks should not be done in the template).

An example how to use it is here, in the default template: https://github.com/IonicaBizau/blah/blob/master/lib/templates/README.ejs

Another example is my template: https://github.com/IonicaBizau/dotfiles/blob/master/blah-templates/README.ejs

Contributions to fix the docs there are welcome, otherwise I will do that one day.
